api = "0.7"

[buildpack]
  description = "A buildpack for building Go applications"
  homepage = "https://github.com/initializ-buildpacks/go"
  id = "initializ-buildpacks/go"
  sbom-formats = [ "application/spdx+json" ]
  keywords = ["go", "golang"]
  name = "Initializ Buildpack for Go"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/go/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.7"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.7"

  [[order.group]]
    id = "initializ-buildpack/go-dist"
    version = "2.4.4"

  [[order.group]]
    id = "initializ-buildpack/git"
    optional = true
    version = "1.0.7"

  [[order.group]]
    id = "initializ-buildpack/go-mod-vendor"
    version = "1.0.27"

  [[order.group]]
    id = "initializ-buildpack/go-build"
    version = "2.1.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.8"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.5"

[[order]]

  [[order.group]]
    id = "paketo-buildpacks/ca-certificates"
    optional = true
    version = "3.6.7"

  [[order.group]]
    id = "paketo-buildpacks/watchexec"
    optional = true
    version = "2.8.7"

  [[order.group]]
    id = "initializ-buildpack/go-dist"
    version = "2.4.4"

  [[order.group]]
    id = "initializ-buildpack/git"
    optional = true
    version = "1.0.7"

  [[order.group]]
    id = "initializ-buildpack/go-build"
    version = "2.1.2"

  [[order.group]]
    id = "paketo-buildpacks/procfile"
    optional = true
    version = "5.6.8"

  [[order.group]]
    id = "paketo-buildpacks/environment-variables"
    optional = true
    version = "4.5.6"

  [[order.group]]
    id = "paketo-buildpacks/image-labels"
    optional = true
    version = "4.5.5"
