api = "0.7"

[buildpack]
  description = "A buildpack for building Go applications"
  homepage = "https://github.com/initializ-buildpacks/go"
  id = "initializ-buildpacks/go"
  keywords = ["go", "golang"]
  name = "Initializ Buildpack for Go"
  sbom-formats = ["application/spdx+json"]

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/initializ-buildpacks/go/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "4.0.5"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.15"

  [[order.group]]
    id = "initializ-buildpacks/go-dist"
    version = "2.5.3"

  [[order.group]]
    id = "initializ-buildpacks/git"
    optional = true
    version = "1.1.0"

  [[order.group]]
    id = "initializ-buildpacks/go-mod-vendor"
    version = "1.1.1"

  [[order.group]]
    id = "initializ-buildpacks/go-build"
    version = "2.2.1"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.21"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.14"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.6.3"

[[order]]

  [[order.group]]
    id = "initializ-buildpacks/ca-certificates"
    optional = true
    version = "4.0.5"

  [[order.group]]
    id = "initializ-buildpacks/watchexec"
    optional = true
    version = "2.8.15"

  [[order.group]]
    id = "initializ-buildpacks/go-dist"
    version = "2.5.3"

  [[order.group]]
    id = "initializ-buildpacks/git"
    optional = true
    version = "1.1.0"

  [[order.group]]
    id = "initializ-buildpacks/go-build"
    version = "2.2.1"

  [[order.group]]
    id = "initializ-buildpacks/procfile"
    optional = true
    version = "5.6.21"

  [[order.group]]
    id = "initializ-buildpacks/environment-variables"
    optional = true
    version = "4.5.14"

  [[order.group]]
    id = "initializ-buildpacks/image-labels"
    optional = true
    version = "4.6.3"
